// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import product "github.com/uudashr/marketplace/internal/product"

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Categories provides a mock function with given fields:
func (_m *CategoryRepository) Categories() ([]*product.Category, error) {
	ret := _m.Called()

	var r0 []*product.Category
	if rf, ok := ret.Get(0).(func() []*product.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*product.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryByID provides a mock function with given fields: id
func (_m *CategoryRepository) CategoryByID(id string) (*product.Category, error) {
	ret := _m.Called(id)

	var r0 *product.Category
	if rf, ok := ret.Get(0).(func(string) *product.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *CategoryRepository) Store(_a0 *product.Category) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*product.Category) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
